# ---------------- =/= ---------------- #
#              LaivyQuests              #
#      This plugin has developed by     #
#    Laivy, created to allow servers    #
#      to make powerful quests and      #
#     increase server entertainment     #
# ---------------- =/= ---------------- #
# Author(s): ItsLaivy (DanielZinh#7616) #
# https://discord.com/invite/Kv7Xvw9HXh #
# ---------------- =/= ---------------- #
#              Permissions              #
# ---------------- =/= ---------------- #
#               Commands                #
# ---------------- =/= ---------------- #

version: ${project.version}
check-updates: true

database:
  type: "SQLITE" # Can be "MYSQL" or "SQLITE"

  mysql:
    database: "quests"
    user: "root"
    password: "password"
    address: "address"
    port: 3306

    table: "quests"
    column: "quests"
  sqlite:
    path: ""

    database: "database"
    table: "quests"
    column: "quests"

menus:
  # If true, the money rewards will be represented with "K", "M", "B", ect...
  money symbol: true