name: "LaivyQuests"
main: "codes.laivy.quests.LaivyQuests"
version: ${project.version}
author: "ItsLaivy (DanielZinh#7616)"
api-version: 1.19

website: "https://laivy.codes/"

commands:
  quests:
    description: "The main quests plugin"
    aliases:
      - quest

softdepend:
  - LvMultiplesLanguages